language: bash
services: docker

env:
  - VERSION=2.6

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
  - cd ~/official-images
  - git reset --hard b65b73e1744c68139339593982460db77b1675b6

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mongo:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
